// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7AVSFo2WfSa5rLpTyzKfkRiCaOTB1NDI',
    appId: '1:1014147855765:web:44b11d4cf3ab5de08d329c',
    messagingSenderId: '1014147855765',
    projectId: 'safetalk-adcc6',
    authDomain: 'safetalk-adcc6.firebaseapp.com',
    storageBucket: 'safetalk-adcc6.firebasestorage.app',
    measurementId: 'G-Z69PV46KXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8JveqZEBEZ6hn89AzeSGYQ-pBzjDz8So',
    appId: '1:1014147855765:android:3e63ca8946053f6e8d329c',
    messagingSenderId: '1014147855765',
    projectId: 'safetalk-adcc6',
    storageBucket: 'safetalk-adcc6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVXisSLPl9EFkpz-ZvoWVzZS5FlDStTHY',
    appId: '1:1014147855765:ios:6e73134004c16fa58d329c',
    messagingSenderId: '1014147855765',
    projectId: 'safetalk-adcc6',
    storageBucket: 'safetalk-adcc6.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVXisSLPl9EFkpz-ZvoWVzZS5FlDStTHY',
    appId: '1:1014147855765:ios:6e73134004c16fa58d329c',
    messagingSenderId: '1014147855765',
    projectId: 'safetalk-adcc6',
    storageBucket: 'safetalk-adcc6.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7AVSFo2WfSa5rLpTyzKfkRiCaOTB1NDI',
    appId: '1:1014147855765:web:380df6c1fef50ded8d329c',
    messagingSenderId: '1014147855765',
    projectId: 'safetalk-adcc6',
    authDomain: 'safetalk-adcc6.firebaseapp.com',
    storageBucket: 'safetalk-adcc6.firebasestorage.app',
    measurementId: 'G-YSRXYHLEPB',
  );
}
